apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PeaversTalentsData
  description: "A data library addon for World of Warcraft that provides daily updated talent export codes from wowcompare.io."
  annotations:
    github.com/project-slug: peavers-warcraft/PeaversTalentsData
spec:
  type: library
  lifecycle: production
  owner: peavers-warcraft
